/* Generated By:JavaCC: Do not edit this line. DOMOTRIXRecognitionConstants.java */
package com.domotrix.language;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DOMOTRIXRecognitionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMAND = 18;
  /** RegularExpression Id. */
  int ENABLE = 19;
  /** RegularExpression Id. */
  int SHOW = 20;
  /** RegularExpression Id. */
  int DISABLE = 21;
  /** RegularExpression Id. */
  int DISABLE_WHAT = 22;
  /** RegularExpression Id. */
  int ENUM = 23;
  /** RegularExpression Id. */
  int WHAT = 24;
  /** RegularExpression Id. */
  int WHERE = 25;
  /** RegularExpression Id. */
  int WHEN = 26;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 27;
  /** RegularExpression Id. */
  int TIME = 28;
  /** RegularExpression Id. */
  int GOOD_MORNING = 29;
  /** RegularExpression Id. */
  int GOOD_NIGHT = 30;
  /** RegularExpression Id. */
  int STRING = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"il\"",
    "\"lo\"",
    "\"la\"",
    "\"i\"",
    "\"gli\"",
    "\"le\"",
    "\"del\"",
    "\"della\"",
    "\"dello\"",
    "\"dell\\\'\"",
    "\"computer\"",
    "\"modalita\"",
    "\"programma\"",
    "<COMMAND>",
    "<ENABLE>",
    "<SHOW>",
    "<DISABLE>",
    "<DISABLE_WHAT>",
    "<ENUM>",
    "<WHAT>",
    "<WHERE>",
    "\"TRA\"",
    "<DECIMAL_LITERAL>",
    "<TIME>",
    "<GOOD_MORNING>",
    "<GOOD_NIGHT>",
    "<STRING>",
    "\".\"",
  };

}
